{% set name = "python-lsp-black" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7eaeab2a377e96a82cc26afe2f8f2e1cf7c6eaefdcdeab026343e2e559dcce9

build:
  number: 0
  skip: True  # [py<37]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - black >=22.3.0
    - python-lsp-server >=1.4.0
    - toml

test:
  imports:
    - pylsp_black
    - pylsp_black.plugin
  requires:
    - pip
  commands:
    - pip check || true    # [not win]
    - pip check || exit /b  # [win]

about:
  home: https://github.com/python-lsp/python-lsp-black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Black plugin for the Python LSP Server
  dev_url: https://github.com/python-lsp/python-lsp-black
  doc_url: https://github.com/python-lsp/python-lsp-black/blob/master/README.md

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - steff456
